name: yafb_reader
description: Yet Another FictionBook Reader
version: 0.0.1
homepage: https://github.com/dkrutskikh/yafb-reader

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^1.10.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
